import discord
from discord import app_commands
from discord.ext import commands
import aiohttp
import json

with open('./config.json', 'r') as config_file:
    config = json.load(config_file)
    TOKEN = config['token']
    GUILD_ID = config['guildId']
    CLIENT_ID = config['clientId']

intents = discord.Intents.default()
intents.guilds = True
intents.guild_messages = True
intents.messages = True
client = commands.Bot(command_prefix='!', intents=intents)

guild = discord.Object(id=GUILD_ID)

@client.event
async def on_ready():
    await client.tree.sync(guild=guild)
    print(f'Logged in as {client.user}!')

@client.tree.command(name='ask', description='Ask therapai a question', guild=guild)
@app_commands.describe(input='What you want to ask')
async def ask(interaction: discord.Interaction, input: str):
    async with aiohttp.ClientSession() as session:
        async with session.post('https://strongermind.olavorw.workers.dev/',
                                json={'input': input},
                                headers={
                                    'Content-Type': 'application/json',
                                    'X-Chat-ID': str(interaction.user.id)
                                }) as response:
            if response.status == 200:
                data = await response.text()
                try:
                    json_response = json.loads(data)
                    if 'response' in json_response:
                        await interaction.response.send_message(json_response['response'])
                    else:
                        await interaction.response.send_message('Error: Invalid response format.')
                except json.JSONDecodeError:
                    await interaction.response.send_message('Error: Unable to parse response.')
            else:
                await interaction.response.send_message('Error: Unable to fetch response.')

@client.tree.command(name='deletedata', description='Delete all data from chat', guild=guild)
async def deletedata(interaction: discord.Interaction):
    async with aiohttp.ClientSession() as session:
        async with session.delete('https://strongermind.olavorw.workers.dev/',
                                  headers={
                                      'Content-Type': 'application/json',
                                      'X-Chat-ID': str(interaction.user.id)
                                  }) as response:
            if response.status == 200:
                await interaction.response.send_message('Data deleted')
            else:
                await interaction.response.send_message('Error: Unable to delete data.')

@client.tree.command(name='tos', description='Gets the terms of service', guild=guild)
async def tos(interaction: discord.Interaction):
    embed = discord.Embed(title="Terms Of Service", description="""
Terms of Service
1. Acceptance of Terms
By using the services provided by StrongerMind.org ("the Service"), you agree to comply with and be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Service. By using the Service, you also agree to waive any rights to pursue legal claims against StrongerMind.org, its affiliates, employees, or partners.

2. Description of Service
The Service allows users to interact with an AI-based mental health assistant. We provide responses generated by AI models to help support mental well-being. The Service is specifically designed for middle and high school students. It is important to note that the Service is not a substitute for professional medical advice, diagnosis, or treatment.

3. User Responsibilities
You agree not to misuse the Service. This includes, but is not limited to, adhering to rate limits, providing accurate information, and refraining from using offensive or harmful language. Users must be at least 13 years of age and should be in middle or high school to use the Service.

4. Rate Limiting
To maintain the quality of service for all users, requests are limited to 20 per minute. Exceeding this limit will result in temporary restrictions from accessing the Service.

5. Disclaimer
The Service is provided "as is" without warranties of any kind, either express or implied. We make no guarantees regarding the accuracy, reliability, or effectiveness of the responses provided by the AI. You use the Service at your own risk, and we disclaim all liability for any outcomes resulting from its use.

6. Limitation of Liability
To the fullest extent permitted by law, StrongerMind.org is not liable for any direct, indirect, incidental, consequential, or special damages or losses resulting from the use of the Service, including but not limited to emotional distress, loss of data, or any other damages, even if we have been advised of the possibility of such damages. In urgent situations, we encourage users to seek immediate help from professional health services.

7. Indemnification
You agree to indemnify and hold harmless StrongerMind.org, its affiliates, employees, and partners from any claims, liabilities, damages, losses, or expenses (including legal fees) arising out of your use of the Service or your violation of these Terms.

8. Changes to the Terms
We reserve the right to modify these Terms at any time. Changes will be communicated via our website, and your continued use of the Service will signify your acceptance of these changes.

9. Contact
For any questions regarding these Terms, please contact us at niyapanch1@gmail.com.
"""
)
    await interaction.response.send_message(embed=embed)

@client.tree.command(name='privacypolicy', description='Gets the privacy policy', guild=guild)
async def privacypolicy(interaction: discord.Interaction):
    embed = discord.Embed(title="Privacy Policy", description="""
1. Information Collection
We collect and store chat histories and usage data in order to improve the Service and provide a personalized experience. Data collected includes user interactions, chat IDs, and messages exchanged.

2. Data Usage
Data collected is used solely to provide and improve the Service. We may analyze chat histories to understand user needs better and improve response quality.

3. Data Storage
Chat histories are stored in our cloud infrastructure and are protected with industry-standard security measures. However, no system is entirely secure, and we cannot guarantee complete security.

4. Sharing of Information
We do not share user data with third parties without consent, except as required by law or to prevent misuse of the Service.

5. User Rights
You have the right to request the deletion of your chat history by contacting us or by using the DELETE request feature available in the Service.

6. Children’s Privacy
The Service is intended for users aged 13 and above who are in middle or high school. We do not knowingly collect personal information from children under 13.

7. Changes to this Policy
We may update this Privacy Policy periodically. Changes will be posted on our website, and your continued use of the Service indicates your acceptance of the revised policy.

8. Disclaimer of Liability
To the fullest extent permitted by law, StrongerMind.org disclaims all liability for any damages or losses resulting from the use of the Service, including but not limited to loss of data, emotional distress, or any other negative impact.

9. Contact
For questions regarding this Privacy Policy, please reach out to us at niyapanch1@gmail.com.
""")
    await interaction.response.send_message(embed=embed)

client.run(TOKEN)
